### ISSUE TITLE
Support fpm

### ISSUE THREAD

**Issue by epagone** [jchristopherson/fplot#16]
I really like this package, especially the fact that is written using modern features. Thanks for sharing it.

I am wondering if there is any plan to support the [Fortran package manager](https://fpm.fortran-lang.org/).

**Comment by jchristopherson** [comment]
Hi @epagone, I'm glad you enjoy this work.  I will work on adding FPM support.  I can't promise a timeline at this point as I would like to utilize FPM on the dependencies of this library as well.  Regardless, thank you for the input, and I will work to add FPM.

**Comment by epagone** [comment]
Thank you

**Comment by jchristopherson** [comment]
Hi @epagone.  I've added FPM support.  Please check it out when you get a chance.

**Comment by epagone** [comment]
Many thanks for such quick action, it works great! :rocket: 

I was fiddling a bit cloning the repository and I created an `example` directory copying inside the first three examples in the `README`, in three individual files, i.e. `example{1,2,3}.f`. Executing
```
fpm run --example example1
```
works if references to method `set_use_auto_color` are commented. Otherwise, the compiler complains that `set_use_auto_color` is not a memeber of `plot_object` . I guess (some of) the examples need to be updated. I'll report this in a separate issue.
