### ISSUE TITLE
Error: ‘set_use_auto_color’ at (1) is not a member of the ‘plot_object’ structure

### ISSUE THREAD

**Issue by epagone** [jchristopherson/fplot#19]
When compiling some tests in the `README`, gfortran complains with the error in the subject. Commenting all references to `set_use_auto_color` make the example compile and run correctly. My best guess is that method is just a leftover from a previous version of the library.

**Comment by jchristopherson** [comment]
Hi @epagone, you are correct that issue was just a leftover from a previous version.  I've updated the README and provided updated plots for all examples.

**Comment by epagone** [comment]
Fantastic, thank you!

**Comment by jchristopherson** [comment]
You’re welcome!
