### ISSUE TITLE
Use `forcolormap`

### ISSUE THREAD

**Issue by epagone** [jchristopherson/fplot#20]
Levereging  the great project [`forcolormap`](https://github.com/vmagnin/forcolormap) (fpm ready) would bring `fplot` to the next level. For the rationale of such effort, please see for example [this](https://www.fabiocrameri.ch/colourmaps/).

**Comment by jchristopherson** [comment]
Nice!  Thanks @epagone for sending this my way!  I'll start playing around with this.

**Comment by jchristopherson** [comment]
Hi @epagone.  Just to let you know, I haven't forgotten about this request.  I'm almost complete in adding support for forcolormap.  It honestly took me a bit to figure out how best to integrate the library, but not break the existing colormap approach used by this library.  I ended up encapsulating a forcolormap object within a fplot colormap type.  I used the name custom_colormap to define this type.  Right now I'm playing with this code on the v1.7 branch, but I'll merge it once I'm complete.

**Comment by epagone** [comment]
Exciting! Thanks for the work, the heads-up and the info.

**Comment by jchristopherson** [comment]
You're welcome.  Stay tuned.  I'll let you know when it's complete.

**Comment by jchristopherson** [comment]
@epagone.  This is now complete.  It's included in release v1.7.0.

**Comment by epagone** [comment]
Thank you! I hope I'll be able to find some time this week to run some tests :rocket:

**Comment by jchristopherson** [comment]
I updated one of the examples in the read me to illustrate the implementation. I used the alias cmap to refer to the forcolormap colormap type to avoid issues with the colormap type already in this library.
